server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/relief_product_stock?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Amcont123!1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/pages/
      suffix: .jsp
minim:
  stock:
    threshold: 50
